project_id = "lgfewsifdmhodjdxojck"

[functions.chat]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.process-notifications]
verify_jwt = false

[functions.nearby-emergency]
verify_jwt = false

[functions.send-panic-alert]
verify_jwt = false

[functions.send-crisis-notification]
verify_jwt = false
